### ISSUE TITLE
Purchase new toolbox and tools

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team-2022#5]
Purchase toolbox and new tools
- Done - Wire Strippers - 
- Toolbox - https://www.homedepot.com/p/Husky-52-in-W-9-Drawer-Deep-Tool-Chest-Mobile-Workbench-in-Gloss-Black-HOTC5209B12M/312145945
- Bench Top drill press - https://www.homedepot.com/p/WEN-10-in-Drill-Press-with-Laser-4210T/308605494
- Hydraulic lift cart - https://www.uline.com/BL_1821/Manual-Lift-Tables  36"x20" double scissor lift H-1784

**Comment by stcoyle137** [comment]
We need wire strippers. Like this [https://www.amazon.com](https://www.amazon.com/WGGE-Professional-crimping-Multi-Tool-Multi-Function/dp/B073YG65N2/ref=sxin_14?asc_contentid=amzn1.osa.c61d4525-0e50-4609-9230-a2e55c7ff10e.ATVPDKIKX0DER.en_US&asc_contenttype=article&ascsubtag=amzn1.osa.c61d4525-0e50-4609-9230-a2e55c7ff10e.ATVPDKIKX0DER.en_US&creativeASIN=B073YG65N2&cv_ct_cx=wire+strippers&cv_ct_id=amzn1.osa.c61d4525-0e50-4609-9230-a2e55c7ff10e.ATVPDKIKX0DER.en_US&cv_ct_pg=search&cv_ct_we=asin&cv_ct_wn=osp-single-source-earns-comm&keywords=wire+strippers&linkCode=oas&pd_rd_i=B073YG65N2&pd_rd_r=a8b84e4a-898d-42c1-8708-6c8fdfc59984&pd_rd_w=0UIOX&pd_rd_wg=GSmiC&pf_rd_p=b029c82c-aced-48fe-b955-08794dc4e3cd&pf_rd_r=B8HRVAZFX7733CNQP68E&qid=1638485963&sr=1-3-a3cc9a7a-2f07-46dc-8259-ac02200376a0&tag=thisoldhouse05-20). Doesn't need to be from Amazon but don't get the auto strippers, they suck.
